cd ..
cd src/experiments/daya_bay/daya_bay_3158days/
julia test.jl
cd -
cd src/experiments/icecube/deepcore_9y_verification_sample/
julia test.jl
cd -
cd src/experiments/juno/
julia test.jl
cd -
cd src/experiments/kamland/kamland_7years/
julia test.jl
cd -
cd src/experiments/km3net/orca6_433kton/
julia test.jl
cd -
cd src/experiments/minos/minos_sterile_16e20_POT/
julia test.jl
cd -
